# Generated by Django 6.0.5 on 2026-06-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0003_message_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tags",
            field=models.ManyToManyField(blank=True, to="messenger.tag"),
        ),
    ]
