# Generated by Django 6.0.5 on 2026-06-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0004_message_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="messages/"),
        ),
    ]
